# Generated by Django 6.0.5 on 2026-05-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='about',
        ),
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
