# Generated by Django 6.0.5 on 2026-05-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_about_about_about_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='homeimg/')),
            ],
        ),
    ]
